name: Manual Trigger dev-deploy.yml

# Configure Manual Trigger
on:
  workflow_dispatch:

jobs:
  deployDev:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ~ Get code from repo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm run test:headless

    - name: Build
      run: npm run build:dev

    - name: FTP Deploy
      if: success()
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.ftp_url }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        local-dir: ./dist/parsidance-website/
        server-dir: /devParsidance/
